apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-deployment
  labels:
    app.kubernetes.io/name: mnist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mnist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mnist
    spec:
      containers:
      - name: mnist
        image: handeanjali/mnist_digit_recognizer:1.0.0.Release
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mnist-service
spec:
  selector:
    app.kubernetes.io/name: mnist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mnist-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: mnist-service
            port:
             number: 80
